sudo: true
language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt-preview
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
cache:
  apt: true

before_install:
  - sudo rm /home/travis/.cargo/registry/ -rf && sudo rm /home/travis/.cargo/git/ -rf
  - wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - xz -d clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz && tar xvf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar
  - cd clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04 && sudo cp -r * /usr/local && cd ..

install:
  - .ci-script/travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

script:
  # For speed up the CI process
  #   See: https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs
  - cargo fmt -- --write-mode check && cargo build --all-features --all && cargo test --all-features --all
