language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt-preview
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
cache:
  cargo: true
  apt: true
  directories:
    - $HOME/libsodium
install:
  - .ci-script/travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

jobs:
  include:
    - stage: Format
      script: cargo fmt -- --write-mode check
    - stage: Build
      script: cargo build --all-features --all
    - stage: Test
      script: cargo test --all-features --all
