[package]
name = "cita-tool"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>", "Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
hyper = "^0.11.26"
tokio-core = "^0.1"
futures = "^0.1"
serde_json = "^1.0.17"
serde = "^1.0.53"
serde_derive = "^1.0.53"
protobuf = "=1.4.4"
