[package]
name = "cita-cli"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>", "Qian Linfeng <thewawar@gmail.com>"]
build = "build.rs"

[dependencies]
dotenv = "^0.11.0"
clap = "^2.31.2"
ansi_term = "^0.10.0"
syntect = "^2.0.1"
rustc-hex = "1.0"
linefeed = "^0.5.0"
ethabi = "^5.1.1"
cita-tool = { path = "../cita-tool" }

[build-dependencies]
clap = "^2.31.2"
cita-tool = { path = "../cita-tool" }

[features]
default = []
blake2b_hash = ["cita-tool/blake2b_hash"]
